FROM golang:1.18-alpine as builder
RUN apk add -U make git
RUN adduser -D -g '' --shell /bin/false moov

# Pull api code into image, then build
WORKDIR /go/src/github.com/moov-io/fed/
COPY . .
RUN make build
USER moov

FROM scratch
LABEL maintainer="Moov <support@moov.io>"

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /go/src/github.com/moov-io/fed/bin/fedtest /bin/fedtest
COPY --from=builder /etc/passwd /etc/passwd

USER moov
EXPOSE 8080
EXPOSE 9090
ENTRYPOINT ["/bin/fedtest"]
