FROM golang:1.12-alpine as builder
RUN apk add -U make git
RUN adduser -D -g '' --shell /bin/false moov

# Clone go-client (rather than vendor)
WORKDIR /go/src/github.com/moov-io/
RUN git clone https://github.com/moov-io/go-client
RUN go get -u github.com/moov-io/go-client/client

# Pull api code into image, then build
WORKDIR /go/src/github.com/moov-io/fed/
COPY . .
ENV GO111MODULE=on
RUN go mod download
RUN make build
USER moov

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /go/src/github.com/moov-io/fed/bin/fedtest /bin/fedtest
COPY --from=builder /etc/passwd /etc/passwd
USER moov
EXPOSE 8080
EXPOSE 9090
ENTRYPOINT ["/bin/fedtest"]
