# Step one: build scapresults
FROM registry.access.redhat.com/ubi8/go-toolset as builder
COPY . .
RUN make build

FROM registry.access.redhat.com/ubi8/ubi-minimal

ARG VERSION=unknown
LABEL maintainer="Moov <support@moov.io>"
LABEL name="fed"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/server /bin/server

COPY data/*.txt /data/fed/

ENV FEDACH_DATA_PATH=/data/fed/FedACHdir.txt
ENV FEDWIRE_DATA_PATH=/data/fed/fpddir.txt

EXPOSE 8086
EXPOSE 9096

ENTRYPOINT ["/bin/server"]
